[{
    "odata.type": "SP.Group",
    "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(26)",
    "odata.editLink": "Web/SiteGroups/GetById(26)",
    "Id": 26, "IsHiddenInUI": false, "LoginName": "AngularDemos Members", "Title":
    "AngularDemos Members", "PrincipalType": 8, "AllowMembersEditMembership":
    true, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Use this group to grant people contribute permissions to the SharePoint site: AngularDemos", "OnlyAllowMembersViewMembership": false, "OwnerTitle": "AngularDemos Owners", "RequestToJoinLeaveEmailSetting": "rgove@rgove3.onmicrosoft.com"
}, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(24)", "odata.editLink": "Web/SiteGroups/GetById(24)", "Id": 24, "IsHiddenInUI": false, "LoginName": "AngularDemos Owners", "Title": "AngularDemos Owners", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Use this group to grant people full control permissions to the SharePoint site: AngularDemos", "OnlyAllowMembersViewMembership": false, "OwnerTitle": "AngularDemos Owners", "RequestToJoinLeaveEmailSetting": "rgove@rgove3.onmicrosoft.com" }, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(25)", "odata.editLink": "Web/SiteGroups/GetById(25)", "Id": 25, "IsHiddenInUI": false, "LoginName": "AngularDemos Visitors", "Title": "AngularDemos Visitors", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Use this group to grant people read permissions to the SharePoint site: AngularDemos", "OnlyAllowMembersViewMembership": false, "OwnerTitle": "AngularDemos Owners", "RequestToJoinLeaveEmailSetting": "rgove@rgove3.onmicrosoft.com" }, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(18)", "odata.editLink": "Web/SiteGroups/GetById(18)", "Id": 18, "IsHiddenInUI": false, "LoginName": "Approvers", "Title": "Approvers", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Members of this group can edit and approve pages, list items, and documents.", "OnlyAllowMembersViewMembership": true, "OwnerTitle": "Owners", "RequestToJoinLeaveEmailSetting": null }, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(16)", "odata.editLink": "Web/SiteGroups/GetById(16)", "Id": 16, "IsHiddenInUI": false, "LoginName": "Designers", "Title": "Designers",
 "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Members of this group can edit lists, document libraries, and pages in the site. Designers can create Master Pages and Page Layouts in the Master Page Gallery and can change the behavior and appearance of each site in the site collection by using master pages and CSS files.  ", "OnlyAllowMembersViewMembership": true, "OwnerTitle": "Owners", "RequestToJoinLeaveEmailSetting": null }, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(7)", "odata.editLink": "Web/SiteGroups/GetById(7)", "Id": 7, "IsHiddenInUI": false, "LoginName": "Excel Services Viewers", "Title": "Excel Services Viewers", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Members of this group can view pages, list items, and documents.  If the document has a server rendering available, they can only view the document using the server rendering.", "OnlyAllowMembersViewMembership": true, "OwnerTitle": "Owners", "RequestToJoinLeaveEmailSetting": null }, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(216)", "odata.editLink": "Web/SiteGroups/GetById(216)", "Id": 216, "IsHiddenInUI": false, "LoginName": "Group_2aca9f2a-82a5-4409-b706-47c3f20aa54b", "Title": "Group_2aca9f2a-82a5-4409-b706-47c3f20aa54b", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "", "OnlyAllowMembersViewMembership": false, "OwnerTitle": "Group_2aca9f2a-82a5-4409-b706-47c3f20aa54b", "RequestToJoinLeaveEmailSetting": null }, {
    "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(232)", "odata.editLink": "Web/SiteGroups/GetById(232)", "Id": 232, "IsHiddenInUI": false,
    "LoginName": "Group_5e4bac3e-a313-46a3-8a30-446f33a251f9",
    "Title": "Group_5e4bac3e-a313-46a3-8a30-446f33a251f9",
    "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "", "OnlyAllowMembersViewMembership": false, "OwnerTitle": "Group_5e4bac3e-a313-46a3-8a30-446f33a251f9", "RequestToJoinLeaveEmailSetting": null
}, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(178)", "odata.editLink": "Web/SiteGroups/GetById(178)", "Id": 178, "IsHiddenInUI": false, "LoginName": "Group_6fb33828-e707-40cf-9708-732042dd067a", "Title": "Group_6fb33828-e707-40cf-9708-732042dd067a", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "", "OnlyAllowMembersViewMembership": false, "OwnerTitle": "Group_6fb33828-e707-40cf-9708-732042dd067a", "RequestToJoinLeaveEmailSetting": null }, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(179)", "odata.editLink": "Web/SiteGroups/GetById(179)", "Id": 179, "IsHiddenInUI": false, "LoginName": "Group_b8f322ac-d324-4d0c-8cb1-57217d5da12e", "Title": "Group_b8f322ac-d324-4d0c-8cb1-57217d5da12e", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "", "OnlyAllowMembersViewMembership": false, "OwnerTitle": "Group_b8f322ac-d324-4d0c-8cb1-57217d5da12e", "RequestToJoinLeaveEmailSetting": null }, {
    "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(180)", "odata.editLink": "Web/SiteGroups/GetById(180)", "Id": 180, "IsHiddenInUI": false, "LoginName": "Group_bd071188-2965-46dd-94b1-cc48604bdc6a",
    "Title": "Group_bd071188-2965-46dd-94b1-cc48604bdc6a",
    "PrincipalType": 8,
    "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false,
    "AutoAcceptRequestToJoinLeave": false, "Description": "",
    "OnlyAllowMembersViewMembership": false,
    "OwnerTitle": "Group_bd071188-2965-46dd-94b1-cc48604bdc6a",
    "RequestToJoinLeaveEmailSetting": null
},
{
    "odata.type": "SP.Group",
    "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(245)",
    "odata.editLink": "Web/SiteGroups/GetById(245)", "Id": 245,
    "IsHiddenInUI": false, "LoginName": "Group_befc9ab1-ddb5-411b-ab6a-255bc000436b",
    "Title": "Group_befc9ab1-ddb5-411b-ab6a-255bc000436b", "PrincipalType": 8,
    "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false,
    "AutoAcceptRequestToJoinLeave": false, "Description": "",
    "OnlyAllowMembersViewMembership": false,
    "OwnerTitle": "Group_befc9ab1-ddb5-411b-ab6a-255bc000436b", "RequestToJoinLeaveEmailSetting": null
}, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(138)", "odata.editLink": "Web/SiteGroups/GetById(138)", "Id": 138, "IsHiddenInUI": false, "LoginName": "Group_df224575-9942-4367-ae5a-30140b7e69a9", "Title": "Group_df224575-9942-4367-ae5a-30140b7e69a9", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "", "OnlyAllowMembersViewMembership": false, "OwnerTitle": "Group_df224575-9942-4367-ae5a-30140b7e69a9", "RequestToJoinLeaveEmailSetting": null }, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(17)", "odata.editLink": "Web/SiteGroups/GetById(17)", "Id": 17, "IsHiddenInUI": false, "LoginName": "Hierarchy Managers", "Title": "Hierarchy Managers", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Members of this group can create sites, lists, list items, and documents. ", "OnlyAllowMembersViewMembership": true, "OwnerTitle": "Owners", "RequestToJoinLeaveEmailSetting": null }, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(5)", "odata.editLink": "Web/SiteGroups/GetById(5)", "Id": 5, "IsHiddenInUI": false, "LoginName": "Members", "Title": "Members", "PrincipalType": 8, "AllowMembersEditMembership": true, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Use this group to grant people contribute permissions to the SharePoint site: ", "OnlyAllowMembersViewMembership": false, "OwnerTitle": "Owners", "RequestToJoinLeaveEmailSetting": "" },
{
    "odata.type": "SP.Group",
    "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(3)",
    "odata.editLink": "Web/SiteGroups/GetById(3)", "Id": 3, "IsHiddenInUI": false,
    "LoginName": "Owners", "Title": "Owners", "PrincipalType": 8,
    "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false,
    "AutoAcceptRequestToJoinLeave": false, "Description": "Use this group to grant people full control permissions to the SharePoint site: ",
    "OnlyAllowMembersViewMembership": false, "OwnerTitle": "Owners",
    "RequestToJoinLeaveEmailSetting": ""
},
{ "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(20)", "odata.editLink": "Web/SiteGroups/GetById(20)", "Id": 20, "IsHiddenInUI": false, "LoginName": "Quick Deploy Users", "Title": "Quick Deploy Users", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Members of this group can schedule Quick Deploy jobs.", "OnlyAllowMembersViewMembership": true, "OwnerTitle": "Owners", "RequestToJoinLeaveEmailSetting": null }, {
    "odata.type": "SP.Group",
    "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(28)",
    "odata.editLink": "Web/SiteGroups/GetById(28)", "Id": 28, "IsHiddenInUI": false,
    "LoginName": "Records Center Web Service Submitters",
    "Title": "Records Center Web Service Submitters",
    "PrincipalType": 8, "AllowMembersEditMembership": false,
    "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false,
    "Description": "Members of this group can submit content to this site using Web Services.",
    "OnlyAllowMembersViewMembership": true,
    "OwnerTitle": "Owners",
    "RequestToJoinLeaveEmailSetting": null
}, {
    "odata.type": "SP.Group",
    "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(19)",
    "odata.editLink": "Web/SiteGroups/GetById(19)", "Id": 19, "IsHiddenInUI": false, "LoginName": "Restricted Readers", "Title": "Restricted Readers", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Members of this group can view pages and documents, but cannot view historical versions or review user rights information.", "OnlyAllowMembersViewMembership": true, "OwnerTitle": "Owners", "RequestToJoinLeaveEmailSetting": null
}, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(15)", "odata.editLink": "Web/SiteGroups/GetById(15)", "Id": 15, "IsHiddenInUI": false, "LoginName": "Style Resource Readers", "Title": "Style Resource Readers", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Use this group to give read permissions to the Master Page gallery and Style Library, which are required to browse this site. Do not delete this group.", "OnlyAllowMembersViewMembership": true, "OwnerTitle": "Owners", "RequestToJoinLeaveEmailSetting": null }, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(136)", "odata.editLink": "Web/SiteGroups/GetById(136)", "Id": 136, "IsHiddenInUI": false, "LoginName": "TEST GROUP", "Title": "TEST GROUP", "PrincipalType": 8,
 "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "", "OnlyAllowMembersViewMembership": true, "OwnerTitle": "russell gove", "RequestToJoinLeaveEmailSetting": null }, { "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(22)", "odata.editLink": "Web/SiteGroups/GetById(22)", "Id": 22, "IsHiddenInUI": false, "LoginName": "Translation Managers", "Title": "Translation Managers", "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false, "AutoAcceptRequestToJoinLeave": false, "Description": "Members of this group can translate pages, list items and documents in Variations.", "OnlyAllowMembersViewMembership": true, "OwnerTitle": "Owners", "RequestToJoinLeaveEmailSetting": null }, {
    "odata.type": "SP.Group", "odata.id": "https://rgove3.sharepoint.com/_api/Web/SiteGroups/GetById(4)", "odata.editLink": "Web/SiteGroups/GetById(4)", "Id": 4, "IsHiddenInUI": false, "LoginName": "Visitors", "Title": "Visitors",
    "PrincipalType": 8, "AllowMembersEditMembership": false, "AllowRequestToJoinLeave": false,
    "AutoAcceptRequestToJoinLeave": false, "Description": "Use this group to grant people read permissions to the SharePoint site: ", "OnlyAllowMembersViewMembership": false, "OwnerTitle": "Owners", "RequestToJoinLeaveEmailSetting": ""
}]"